[build]
  command = "npm run static"
  publish = "out"

[context.production]
  environment = { HASHI_ENV = "production", NODE_ENV = "production" }

[context.deploy-preview]
  environment = { HASHI_ENV = "staging", NODE_ENV = "production" }

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.images]
  compress = true

[build.processing.html]
  pretty_urls = true
